/**
 * Stable REST API error `code` strings — aligned with
 * `../FlumeTV-API/src/constants/errorCodes.constants.ts`.
 */

export const REST_ERROR_CODES = {
  REGISTER_PASSWORD_INVALID: "REGISTER_PASSWORD_INVALID",
  REGISTER_FAILED: "REGISTER_FAILED",
  AUTH_SERVER_MISCONFIGURED: "AUTH_SERVER_MISCONFIGURED",
  REGISTER_USER_ID_CONFLICT: "REGISTER_USER_ID_CONFLICT",
  AUTH_BODY_INVALID: "AUTH_BODY_INVALID",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_SESSION_MISSING: "AUTH_SESSION_MISSING",
  AUTH_SESSION_INVALID: "AUTH_SESSION_INVALID",
  CONFIG_BODY_INVALID: "CONFIG_BODY_INVALID",
  CONFIG_ALREADY_EXISTS: "CONFIG_ALREADY_EXISTS",
  QUEUE_BACKLOG_EXCEEDED: "QUEUE_BACKLOG_EXCEEDED",
  HASH_SYNC_ALREADY_ACTIVE: "HASH_SYNC_ALREADY_ACTIVE",
  HASH_CONFIG_NOT_FOUND: "HASH_CONFIG_NOT_FOUND",
  HASH_NOT_LINKED_TO_USER: "HASH_NOT_LINKED_TO_USER",
  HASH_CANCEL_NOT_AUTHORIZED: "HASH_CANCEL_NOT_AUTHORIZED",
  HASH_NO_ACTIVE_SYNC_TO_CANCEL: "HASH_NO_ACTIVE_SYNC_TO_CANCEL",
  CHANGE_PASSWORD_BODY_INVALID: "CHANGE_PASSWORD_BODY_INVALID",
  CHANGE_PASSWORD_CURRENT_INVALID: "CHANGE_PASSWORD_CURRENT_INVALID",
} as const;

/** Client-only codes when axios has no REST `{ code, message }` envelope. */
export const REST_API_FALLBACK_CODES = {
  REQUEST_TIMEOUT: "REQUEST_TIMEOUT",
  NETWORK_UNREACHABLE: "NETWORK_UNREACHABLE",
  UNKNOWN: "UNKNOWN",
} as const;
